language: generic 

sudo: required

services:
  - docker

before_install:
  - docker build -t sardar472003/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sardar472003/docker-react npm run test